### ISSUE TITLE
Universal Viewer https://universalviewer.io/

### ISSUE THREAD

**Issue by mberkowski** [UMNLibraries/cdm-blacklightify#10]
### Kaltura transcription example
* https://specialcollections.du.edu/object/416aac52-de61-4c86-b329-32663c355789#?c=&m=&s=&cv= 
* DU digital collections repository: https://github.com/dulibrarytech/digitaldu-frontend

### Accessibility testing
[UV's accessibility statement](https://github.com/UniversalViewer/universalviewer/wiki/Accessibility-Statement-for-the-Universal-Viewer) tl;dr they know of some problem areas.

**Comment by puzumaki** [comment]
We'll need to discuss how broadly to test this tool because this page has significant errors on a preliminary automated scan.

**Comment by mberkowski** [comment]
Oh this is ambiguous, an artifact of me just quickly converting a board card into an issue. The specific du.edu Kaltura implementation is not what we're interested about in evaluating. It's just an example of how the transcription implementation is done in conjunction with UV.

We will be concerned with a11y eval on universal viewer when setup independently on our own pages or test lab.

**Comment by ewlarson** [comment]
Just a note: The Kaltura transcription plugin should be enabled for:

UL - UMedia | Single audio -- id = 42156071
UL - UMedia | Video, Video Playlist, Audio Playlist -- id = 41902002

**Comment by sourslaw** [comment]
Universal Viewer has been implementing.

Closing this specific issue; however, other related issues regarding accessibility, in-text search can be created separate from this
