### ISSUE TITLE
Spotlight error

### ISSUE THREAD

**Issue by tantz001** [UMNLibraries/cdm-blacklightify#38]
### Descriptive summary

the page http://localhost:3000/spotlight/<exhibit_slug>/catalog/admin

### Expected behavior

should see a list of items in the exhibit

### Actual behavior

rails error page

### Steps to reproduce the behavior

1. create a spotlight exhibit
2. go to http://localhost:3000/spotlight/<exhibit-slug>/edit
3. click on the 'items' link

### Related work

Link to related tickets or prior related work here.

**Comment by sourslaw** [comment]
Closing due to age.
