### ISSUE TITLE
UMedia homepage mockup

### ISSUE THREAD

**Issue by mberkowski** [UMNLibraries/cdm-blacklightify#4]
Create a static mockup of the UMedia homepage with equivalent features it has now, adapting the Design System

**Comment by puzumaki** [comment]
Do you have a timeline for this yet?

**Comment by mberkowski** [comment]
@puzumaki Not firmly. Hardly even loosely. We're viewing this like a project for the whole calendar year 2022.

**Comment by sourslaw** [comment]
Closing due to age.

These homepage mock ups are still available to view: [here](https://docs.google.com/presentation/d/1xzJ6PP_BWTdff-mrbANStvVEfGnvGszhjiISTBR0vGw/edit#slide=id.p)
