### ISSUE TITLE
Rake task to download specified Universal Viewer into public/ dir

### ISSUE THREAD

**Issue by mberkowski** [UMNLibraries/cdm-blacklightify#40]

**Comment by ewlarson** [comment]
I think we might be best loading UV from a CDN here:
https://github.com/UMNLibraries/cdm-blacklightify/pull/61/commits/b2bed09e85800eb54856cd0dc29dc781dc7c668a

Yarn and UV don't quite mix well enough, and the CDN providers will build a dist directory with everything we really need.

**Comment by mberkowski** [comment]
Thanks @ewlarson
