### ISSUE TITLE
Item - Attachments View

### ISSUE THREAD

**Issue by ewlarson** [UMNLibraries/cdm-blacklightify#49]
### Descriptive summary

Add the "Attachments" button behavior from UMedia. Seen in the codebase here:
https://github.com/UMNLibraries/umedia/blob/develop/app/views/items/_metadata.html.erb#L23-L27

**Comment by ewlarson** [comment]
**Attachment - Example Fixture**
https://umedia.lib.umn.edu/item/p16022coll535:222

Pulls PDF from CDM via getfile:
https://cdm16022.contentdm.oclc.org/utils/getfile/collection/p16022coll535/id/222/filename/227.pdf

**Comment by sourslaw** [comment]
Closing due to age
