### ISSUE TITLE
Broken Facets 

### ISSUE THREAD

**Issue by theberg75** [UMNLibraries/cdm-blacklightify#78]
### Descriptive summary

Object-level metadata fields that should be faceted are not working properly. See: https://umedia.lib.umn.edu/item/p16022coll621:222?facets%5Bcollection_name_s%5D%5B%5D=Records+of+YMCA+International+Work+in+Egypt

Check out any faceted fields: Date Created; Creator; Subjects; Parent Collection; etc. (All fields in record including collection name at bottom). This is happening for all objects across collections / contributors.

**Comment by mberkowski** [comment]
Fixed in f02232956ebad764ffbe70301791a0a569d01231 - a boolean logic issue was returning the actual boolean value when deciding whether to print a facet link instead of printing the field name to facet on.
