### ISSUE TITLE
solr-wrapper should be configured for 127.0.0.1 only

### ISSUE THREAD

**Issue by mberkowski** [UMNLibraries/cdm-blacklightify#8]
### Descriptive summary

In development, solr_wrapper is starting Solr on all interfaces, potentially exposing a dev Solr core to the outside Internet if not properly firewalled.

### Expected behavior

Dev Solr is only available to localhost on 127.0.0.1

### Actual behavior

Dev Solr is available on all IPv4 addresses associated with the dev machine

### Steps to reproduce the behavior

1. Start Solr  `bundle exec solr_wrapper --config .solr_wrapper.yml`
1. Find your workstation's IP address
2. Open a connection to the IP and verify Solr is listening `telnet your.ip.address 8983`

**Comment by mberkowski** [comment]
fixed in 785762a

**Comment by ewlarson** [comment]
Closing via https://github.com/UMNLibraries/cdm-blacklightify/pull/9
