### ISSUE TITLE
New object viewer (ideally Universal Viewer).

### ISSUE THREAD

**Issue by theberg75** [UMNLibraries/cdm-blacklightify#82]
UMedia needs a more user friendly object viewer. The functionality of something like universal viewer is highly desirable. An (ideal) key feature of this viewer is the ability to set 1up or 2up page view at the object-level during upload.
In other words, can TB as the person who uploads material, set the viewer to 1up or 2up based on the content /format to better help the user navigate the object. Further thoughts on this:
- Does this become a manual switch that happens during upload? 
- Can we set up a rule where this is determined by a specific field in CDM? (Specific values in the format field, for example, trigger 1up or 2up; example: photograph = 1up; journal = 2up, etc, etc)

**Comment by sourslaw** [comment]
Closing due to age. Universal Viewer has been implemented
