### ISSUE TITLE
Item-level object view: make "Publisher" searchable /hyperlinked 

### ISSUE THREAD

**Issue by theberg75** [UMNLibraries/cdm-blacklightify#99]
Request: publisher is hyperlinked (searchable) in item-level view for any items using this field

(Logic: useful for book historians; also, for artifacts/objects, we use publisher for manufacturer, so it's a key piece of metadata for that item type, especially when thinking about provenance).

**Comment by mberkowski** [comment]
Fixed in 10daf20, will be applied when lang-support branch is merged
